grate-driver/libdrm

tegra/Makefile.am, tegra/channel.c, tegra/fence.c, tegra/job.c, tegra/private.h, tegra/pushbuf.c, tegra/tegra-symbol-check, tegra/tegra.c, tegra/tegra.h
Switch to the actual libdrm-tegra interface that is already used by opentegra and recent mesa rebase. It's pretty minimal right now, but has all basic features. We'll add BO caching, dmabuf support and other stuff on an as-needed basis later.
=> Actualize libdrm-tegra

tegra/pushbuf.c
It was inverted, causing a failure on a job submission if there is more
than one pushbuf contained in the job.
=> tegra: Fix pushbufs list order

tegra/job.c
The jobs syncpot initialization is absent, so the syncpoint ID 0 is used
regardless of the channels client. That's not good for the case of
multiple channels working simultaneously.
=> tegra: Initialize jobs syncpoint to the channels one

tegra/Makefile.am, tegra/channel.c, tegra/fence.c, tegra/job.c, tegra/private.h, tegra/pushbuf.c, tegra/tegra-symbol-check, tegra/tegra.c, tegra/tegra.h, tegra/tegra_bo_cache.c
I've rebased the libdrm on the @thierryreding recent work from freedesktop.org, the old fixes still apply here and some new were added, new features were added as well (BO caching, dmabuf functions). The BO caching gives a significant performance boost to opentegra, drm_tegra_bo_to_dmabuf was tested by VDPAU driver.
=> Restore old functionality + some new

tegra/pushbuf.c
Valgring detects false positive memory leak due to a BO mmap'ing
disbalance caused by a latest-appended pushbufs BO double unmapping
in drm_tegra_pushbuf_queue() and then in drm_tegra_pushbuf_free().
Only the latest-appended pushbufs BO is destroyed in pushbuf_free(),
obviously that's an accidental copy-paste bug.
=> tegra: Correct pushbufs BO mmap'ing balance and free'ing

tegra/private.h, tegra/tegra.c
An atomic mmap'ing refcount doesn't prevent race conditions at all,
a proper locking is required instead.
=> tegra: Thread-safe BO memory mapping

tegra/private.h, tegra/pushbuf.c, tegra/tegra.c
Commit 1efbd61 (Thread-safe BO memory mapping) introduced locking for BO's
memory map / unmap, but missed locking around bo->map on unmapping.
=> Hashtable lookups and some fixes

tegra/tegra_bo_cache.c
In lookup_bo() we are removing BO from cache if it resides in the cache,
however if that BO was re-used from the cache and is in-use during
lookup_bo() invocation, the BO's linked-list next/prev pointers would be
invalid, causing nasty BO cache-list corruption.
=> tegra: Use DRMLISTDELINIT in find_in_bucket

tegra/tegra.c
This fixes a compilation-error when valgrind-headers are not
available.
Signed-off-by: Erik Faye-Lund <kusmabite@gmail.com>
=> tegra: guard valgrind macros with HAVE_VALGRIND

tegra/tegra.c
The lseek() may fail returning a -1 and setting errno, let's not ignore
its failure.
=> tegra: Do not ignore lseek's error

tegra/private.h, tegra/tegra.c, tegra/tegra_bo_cache.c
Let's use macros for BO mmapping / unmapping for consistency with the reset
of valgrind related stuff. Let's disable accessing to mmap region until BO
has been actually mmap'ed using drm_tegra_bo_map.
=> tegra: Refactor and harden valgrind's mmaping a tad

tegra/tegra.c
Mikko Perttunen tried to run Opentegra on TX1 that is 64bit arch and it
failed on drm_tegra_bo_map(), Thierry Reding pointed that drmOpen() isn't
well suited for the 64bit because drm_handle_t (mmap offset) is 32bit,
let's return back to bare mmap() to fix the issue.
This reverts commit cc2c7e4ae101458201a88ab709215746b72f21b3.
=> Revert "tegra: Switch to use of drmMap / drmUnmap"

tegra/private.h, tegra/tegra.c
VG_BO_ALLOC() should be outside of table lock because it invokes
drm_tegra_bo_map() that takes the same lock.
=> tegra: Fix lockups under valgrind

tegra/job.c
This would avoid crashing/corruption in a case of reallocation failure.
=> tegra: Correct typo in drm_tegra_job_add_reloc

tegra/private.h, tegra/tegra.c, tegra/tegra_bo_cache.c
Implement deferred BO unmapping in a way deferred BO freeing is done for BO's caching.
This improves overall performance quite significantly.
=> tegra: Cache BO mappings

tegra/private.h
The taken from cache BO may retain mapping, so we need to restore access to the mapping to fix valgrind's complaining.
==2796== Block 0x4027000..0x402afff overlaps with block 0x4027000..0x402afff
==2796== Blocks allocation contexts:
==2796==    at 0x558290C: VG_BO_OBTAIN (private.h:226)
==2796==    by 0x558290C: is_idle (tegra_bo_cache.c:136)
==2796==    by 0x558290C: find_in_bucket (tegra_bo_cache.c:163)
==2796==    by 0x558290C: drm_tegra_bo_cache_alloc (tegra_bo_cache.c:206)
==2796==    by 0x5581767: drm_tegra_bo_new (tegra.c:165)
==2796==    by 0x556551B: dumb_bo_create (drmmode_display.c:44)
==2796==    by 0x5566523: drmmode_create_initial_bos (drmmode_display.c:1621)
==2796==    by 0x5561FBB: TegraScreenInit (driver.c:827)
==2796==    by 0x15155B: AddScreen (dispatch.c:3910) …
=> tegra: Re-acquire BO mapping in valgrind

tegra/tegra.c
Forbidding caching of BO's after getting dmabuf FD or flink name isn't
a good strategy and prevents libvdpau-tegra from caching. We have a handle
for explicitly forbidding caching of a particular BO, let's don't mess with
the BO's caching in libdrm and instead let the user to decide what BO's
shouldn't be cached.
=> drm/tegra: Don't forbid caching of potentially exported BO's

tegra/private.h, tegra/tegra.c, tegra/tegra_bo_cache.c
The taken out from cache BO may retain memory mapping and since the mmap
refcount is reset, BO mapping should be marked as unmapped under valgrind
to avoid complaining about double mmaping on further BO memory mapping.
==755== Block 0x152ca000..0x153c9fff overlaps with block 0x152ca000..0x153c9fff
==755== Blocks allocation contexts:
==755==    at 0x14AA103C: VG_BO_OBTAIN (private.h:230)
==755==    by 0x14AA103C: reset_bo (tegra_bo_cache.c:180)
==755==    by 0x14AA103C: drm_tegra_bo_cache_alloc (tegra_bo_cache.c:213)
==755==    by 0x14A9FB07: drm_tegra_bo_new (tegra.c:166)
==755==    by 0x48733EB: host1x_pixelbuffer_create (host1x-pixelbuffer.c:102)
==755==    by 0x486E73F: alloc_surface_data (surface.c:136)
==755==    by 0x486EDEF: alloc_surface (surface.c:384)
==755==    by 0x486E233: …
=> tegra: Unmap cached BO on reset under valgrind

tegra/tegra-symbol-check
Fix a typo and add missed function to tegra-symbol-check, this fixes 'make check'.
=> tegra: correct symbols checking

tegra/tegra-symbol-check
Remove drm_tegra_bo_forbid_caching that was added by accident in commit 4784227adba8 ("correct symbols checking").
=> tegra: Really correct symbols checking

tegra/private.h, tegra/tegra.c, tegra/tegra_bo_cache.c
Context switching from / to kernel mode isn't super-cheap, let's avoid unnecessary switches on BO reset, which may happen quite often.
=> tegra: Avoid unnecessary context switches on BO reset

tegra/tegra.c, tegra/tegra_bo_cache.c
Add missed cached BO's debug number decrement for taken out from cache BO.
=> tegra: Correct cached BO's counting

tegra/meson.build
Add missed source files to meson.build to fix compilation using meson.
=> tegra: Fix compilation using meson

tegra/private.h
This fixes "large-stack-frame-growth limit reached.." compilation warning.
=> drm/tegra: Remove some of explicit inline's

tegra/private.h, tegra/tegra.c
Silence compilation warnings for a 64bit target.
=> drm/tegra: Correct formatting of debug messages

tegra/tegra.c
Silence a longstanding harmless warning caused by -Wstrict-aliasing.
=> tegra: Silence compilation warning
